blueprint:
  name: Blocca accensione termostato se finestra è aperta
  description: Spegne il termostato se qualcuno prova ad accenderlo mentre la finestra è aperta.
  domain: automation
  input:
    sensore_finestra:
      name: Sensore finestra
      selector:
        entity:
          domain: binary_sensor
    termostato:
      name: Termostato da controllare
      selector:
        entity:
          domain: climate

trigger:
  - platform: state
    entity_id: !input termostato
    to:
      - 'auto'
      - 'heat'
      - 'cool'

variables:
  input_termostato: !input termostato
  input_sensore_finestra: !input sensore_finestra

condition:
  - condition: template
    value_template: "{{ is_state(input_sensore_finestra, 'on') }}"

action:
  - service: climate.turn_off
    target:
      entity_id: "{{ input_termostato }}"

