blueprint:
  name: Ripristina stato termostato se finestra si chiude
  description: Ripristina il termostato allo stato precedente salvato quando la finestra viene chiusa.
  domain: automation
  input:
    sensore_finestra:
      name: Sensore finestra
      selector:
        entity:
          domain: binary_sensor
    termostato:
      name: Termostato da riaccendere
      selector:
        entity:
          domain: climate
    stato_salvato:
      name: Input Select con lo stato salvato
      selector:
        entity:
          domain: input_select

trigger:
  - platform: state
    entity_id: !input sensore_finestra
    to: 'off'

variables:
  input_termostato: !input termostato
  input_stato_salvato: !input stato_salvato

condition:
  - condition: template
    value_template: "{{ states(input_stato_salvato) in ['auto', 'heat', 'cool'] }}"

action:
  - service: climate.set_hvac_mode
    target:
      entity_id: "{{ input_termostato }}"
    data:
      hvac_mode: "{{ states(input_stato_salvato) }}"

