blueprint:
  name: Spegni termostato e salva stato se finestra si apre
  description: Spegne il termostato e salva il suo stato in un input_select quando si apre una finestra.
  domain: automation
  input:
    sensore_finestra:
      name: Sensore finestra
      selector:
        entity:
          domain: binary_sensor
    termostato:
      name: Termostato da spegnere
      selector:
        entity:
          domain: climate
    stato_salvato:
      name: Input Select dove salvare lo stato
      selector:
        entity:
          domain: input_select

trigger:
  - platform: state
    entity_id: !input sensore_finestra
    to: 'on'

variables:
  input_termostato: !input termostato
  input_stato_salvato: !input stato_salvato

action:
  - choose:
      - conditions:
          #- condition: template
           # value_template: "{{ states(input_termostato) != 'off' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: "{{ input_stato_salvato }}"
            data:
              option: "{{ states(input_termostato) }}"
  - service: climate.turn_off
    target:
      entity_id: "{{ input_termostato }}"

